//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEWEManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftWareInfo
    {
        public int ID { get; set; }
        public string NameCH { get; set; }
        public string NameEN { get; set; }
        public string NameData { get; set; }
        public string DataConnectionTest { get; set; }
        public string DataConnectionOnline { get; set; }
        public string ComputerID { get; set; }
        public string ComputerName { get; set; }
        public string CodeFilePath { get; set; }
        public string DateFilePath { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Remark { get; set; }
    }
}
